import type { Syllable } from '../../types/toneSequence';

/**
 * Mandarin Pinyin Syllable Inventory with Phonetic Difficulty Ratings
 *
 * Difficulty Scoring Heuristic (1-5 scale):
 *
 * Base score: 1
 *
 * Add +1 for each:
 * - Retroflex initials (zh, ch, sh, r) - require tongue curling
 * - Alveolo-palatal initials (j, q, x) - require precise tongue placement
 * - High front vowels in constrained contexts (ü, -i after zh/ch/sh/r/z/c/s)
 * - Complex finals with multiple vowel/glide transitions (iang, iong, uang, etc.)
 *
 * Add +0.5 for each:
 * - Nasal finals (-n, -ng) - require proper nasal resonance
 * - Rounded vowels (o, u) in certain combinations
 * - Erhua (r-coloring, if included)
 *
 * Maximum score capped at 5 for very challenging combinations.
 *
 * This heuristic can be easily modified by adjusting the syllable array below.
 */

export const SYLLABLE_INVENTORY: Syllable[] = [
  // Zero initial
{ pinyin: 'a', difficulty: 1 },
{ pinyin: 'ai', difficulty: 1 },
{ pinyin: 'an', difficulty: 2 },
{ pinyin: 'ang', difficulty: 2 },
{ pinyin: 'ao', difficulty: 1 },
{ pinyin: 'e', difficulty: 1 },
{ pinyin: 'ei', difficulty: 1 },
{ pinyin: 'en', difficulty: 2 },
{ pinyin: 'eng', difficulty: 2 },
{ pinyin: 'er', difficulty: 3 },
{ pinyin: 'o', difficulty: 1 },
{ pinyin: 'ou', difficulty: 1 },

// b
{ pinyin: 'ba', difficulty: 1 },
{ pinyin: 'bai', difficulty: 1 },
{ pinyin: 'ban', difficulty: 2 },
{ pinyin: 'bang', difficulty: 2 },
{ pinyin: 'bao', difficulty: 1 },
{ pinyin: 'bei', difficulty: 1 },
{ pinyin: 'ben', difficulty: 2 },
{ pinyin: 'beng', difficulty: 2 },
{ pinyin: 'bi', difficulty: 2 },
{ pinyin: 'bian', difficulty: 3 },
{ pinyin: 'biao', difficulty: 3 },
{ pinyin: 'bie', difficulty: 2 },
{ pinyin: 'bin', difficulty: 3 },
{ pinyin: 'bing', difficulty: 3 },
{ pinyin: 'bo', difficulty: 2 },
{ pinyin: 'bu', difficulty: 1 },

// p
{ pinyin: 'pa', difficulty: 1 },
{ pinyin: 'pai', difficulty: 1 },
{ pinyin: 'pan', difficulty: 2 },
{ pinyin: 'pang', difficulty: 2 },
{ pinyin: 'pao', difficulty: 1 },
{ pinyin: 'pei', difficulty: 1 },
{ pinyin: 'pen', difficulty: 2 },
{ pinyin: 'peng', difficulty: 2 },
{ pinyin: 'pi', difficulty: 2 },
{ pinyin: 'pian', difficulty: 3 },
{ pinyin: 'piao', difficulty: 3 },
{ pinyin: 'pie', difficulty: 2 },
{ pinyin: 'pin', difficulty: 3 },
{ pinyin: 'ping', difficulty: 3 },
{ pinyin: 'po', difficulty: 2 },
{ pinyin: 'pu', difficulty: 1 },

// m
{ pinyin: 'ma', difficulty: 1 },
{ pinyin: 'mai', difficulty: 1 },
{ pinyin: 'man', difficulty: 2 },
{ pinyin: 'mang', difficulty: 2 },
{ pinyin: 'mao', difficulty: 1 },
{ pinyin: 'mei', difficulty: 1 },
{ pinyin: 'men', difficulty: 2 },
{ pinyin: 'meng', difficulty: 2 },
{ pinyin: 'mi', difficulty: 2 },
{ pinyin: 'mian', difficulty: 3 },
{ pinyin: 'miao', difficulty: 3 },
{ pinyin: 'mie', difficulty: 2 },
{ pinyin: 'min', difficulty: 3 },
{ pinyin: 'ming', difficulty: 3 },
{ pinyin: 'mo', difficulty: 2 },
{ pinyin: 'mu', difficulty: 1 },

// f
{ pinyin: 'fa', difficulty: 1 },
{ pinyin: 'fan', difficulty: 2 },
{ pinyin: 'fang', difficulty: 2 },
{ pinyin: 'fei', difficulty: 1 },
{ pinyin: 'fen', difficulty: 2 },
{ pinyin: 'feng', difficulty: 2 },
{ pinyin: 'fo', difficulty: 3 },
{ pinyin: 'fou', difficulty: 2 },
{ pinyin: 'fu', difficulty: 1 },

// d
{ pinyin: 'da', difficulty: 1 },
{ pinyin: 'dai', difficulty: 1 },
{ pinyin: 'dan', difficulty: 2 },
{ pinyin: 'dang', difficulty: 2 },
{ pinyin: 'dao', difficulty: 1 },
{ pinyin: 'de', difficulty: 1 },
{ pinyin: 'dei', difficulty: 2 },
{ pinyin: 'den', difficulty: 3 },
{ pinyin: 'deng', difficulty: 2 },
{ pinyin: 'di', difficulty: 2 },
{ pinyin: 'dia', difficulty: 4 },
{ pinyin: 'dian', difficulty: 3 },
{ pinyin: 'diao', difficulty: 3 },
{ pinyin: 'die', difficulty: 2 },
{ pinyin: 'ding', difficulty: 3 },
{ pinyin: 'diu', difficulty: 4 },
{ pinyin: 'dong', difficulty: 2 },
{ pinyin: 'dou', difficulty: 1 },
{ pinyin: 'du', difficulty: 1 },
{ pinyin: 'duan', difficulty: 3 },
{ pinyin: 'dui', difficulty: 2 },
{ pinyin: 'dun', difficulty: 2 },
{ pinyin: 'duo', difficulty: 2 },

// t
{ pinyin: 'ta', difficulty: 1 },
{ pinyin: 'tai', difficulty: 1 },
{ pinyin: 'tan', difficulty: 2 },
{ pinyin: 'tang', difficulty: 2 },
{ pinyin: 'tao', difficulty: 1 },
{ pinyin: 'te', difficulty: 1 },
{ pinyin: 'teng', difficulty: 2 },
{ pinyin: 'ti', difficulty: 2 },
{ pinyin: 'tian', difficulty: 3 },
{ pinyin: 'tiao', difficulty: 3 },
{ pinyin: 'tie', difficulty: 2 },
{ pinyin: 'ting', difficulty: 3 },
{ pinyin: 'tong', difficulty: 2 },
{ pinyin: 'tou', difficulty: 1 },
{ pinyin: 'tu', difficulty: 1 },
{ pinyin: 'tuan', difficulty: 3 },
{ pinyin: 'tui', difficulty: 2 },
{ pinyin: 'tun', difficulty: 2 },
{ pinyin: 'tuo', difficulty: 2 },

// n
{ pinyin: 'na', difficulty: 1 },
{ pinyin: 'nai', difficulty: 1 },
{ pinyin: 'nan', difficulty: 2 },
{ pinyin: 'nang', difficulty: 2 },
{ pinyin: 'nao', difficulty: 1 },
{ pinyin: 'ne', difficulty: 1 },
{ pinyin: 'nei', difficulty: 1 },
{ pinyin: 'nen', difficulty: 2 },
{ pinyin: 'neng', difficulty: 2 },
{ pinyin: 'ni', difficulty: 2 },
{ pinyin: 'nian', difficulty: 3 },
{ pinyin: 'niang', difficulty: 3 },
{ pinyin: 'niao', difficulty: 3 },
{ pinyin: 'nie', difficulty: 2 },
{ pinyin: 'nin', difficulty: 3 },
{ pinyin: 'ning', difficulty: 3 },
{ pinyin: 'nong', difficulty: 2 },
{ pinyin: 'nou', difficulty: 2 },
{ pinyin: 'nu', difficulty: 2 },
{ pinyin: 'nuan', difficulty: 4 },
{ pinyin: 'nüe', difficulty: 5 },
{ pinyin: 'nuo', difficulty: 2 },

// l
{ pinyin: 'la', difficulty: 1 },
{ pinyin: 'lai', difficulty: 1 },
{ pinyin: 'lan', difficulty: 2 },
{ pinyin: 'lang', difficulty: 2 },
{ pinyin: 'lao', difficulty: 1 },
{ pinyin: 'le', difficulty: 1 },
{ pinyin: 'lei', difficulty: 1 },
{ pinyin: 'leng', difficulty: 2 },
{ pinyin: 'li', difficulty: 2 },
{ pinyin: 'lia', difficulty: 4 },
{ pinyin: 'lian', difficulty: 3 },
{ pinyin: 'liang', difficulty: 3 },
{ pinyin: 'liao', difficulty: 3 },
{ pinyin: 'lie', difficulty: 2 },
{ pinyin: 'lin', difficulty: 3 },
{ pinyin: 'ling', difficulty: 3 },
{ pinyin: 'liu', difficulty: 3 },
{ pinyin: 'long', difficulty: 2 },
{ pinyin: 'lou', difficulty: 1 },
{ pinyin: 'lu', difficulty: 2 },
{ pinyin: 'luan', difficulty: 3 },
{ pinyin: 'lüe', difficulty: 5 },
{ pinyin: 'lun', difficulty: 2 },
{ pinyin: 'luo', difficulty: 2 },

// g
{ pinyin: 'ga', difficulty: 1 },
{ pinyin: 'gai', difficulty: 1 },
{ pinyin: 'gan', difficulty: 2 },
{ pinyin: 'gang', difficulty: 2 },
{ pinyin: 'gao', difficulty: 1 },
{ pinyin: 'ge', difficulty: 1 },
{ pinyin: 'gei', difficulty: 1 },
{ pinyin: 'gen', difficulty: 2 },
{ pinyin: 'geng', difficulty: 2 },
{ pinyin: 'gong', difficulty: 2 },
{ pinyin: 'gou', difficulty: 1 },
{ pinyin: 'gu', difficulty: 1 },
{ pinyin: 'gua', difficulty: 2 },
{ pinyin: 'guai', difficulty: 2 },
{ pinyin: 'guan', difficulty: 2 },
{ pinyin: 'guang', difficulty: 2 },
{ pinyin: 'gui', difficulty: 2 },
{ pinyin: 'gun', difficulty: 2 },
{ pinyin: 'guo', difficulty: 2 },

// k
{ pinyin: 'ka', difficulty: 1 },
{ pinyin: 'kai', difficulty: 1 },
{ pinyin: 'kan', difficulty: 2 },
{ pinyin: 'kang', difficulty: 2 },
{ pinyin: 'kao', difficulty: 1 },
{ pinyin: 'ke', difficulty: 1 },
{ pinyin: 'ken', difficulty: 2 },
{ pinyin: 'keng', difficulty: 2 },
{ pinyin: 'kong', difficulty: 2 },
{ pinyin: 'kou', difficulty: 1 },
{ pinyin: 'ku', difficulty: 1 },
{ pinyin: 'kua', difficulty: 2 },
{ pinyin: 'kuai', difficulty: 2 },
{ pinyin: 'kuan', difficulty: 2 },
{ pinyin: 'kuang', difficulty: 2 },
{ pinyin: 'kui', difficulty: 2 },
{ pinyin: 'kun', difficulty: 2 },
{ pinyin: 'kuo', difficulty: 2 },

// h
{ pinyin: 'ha', difficulty: 1 },
{ pinyin: 'hai', difficulty: 1 },
{ pinyin: 'han', difficulty: 2 },
{ pinyin: 'hang', difficulty: 2 },
{ pinyin: 'hao', difficulty: 1 },
{ pinyin: 'he', difficulty: 1 },
{ pinyin: 'hei', difficulty: 1 },
{ pinyin: 'hen', difficulty: 2 },
{ pinyin: 'heng', difficulty: 2 },
{ pinyin: 'hong', difficulty: 2 },
{ pinyin: 'hou', difficulty: 1 },
{ pinyin: 'hu', difficulty: 1 },
{ pinyin: 'hua', difficulty: 2 },
{ pinyin: 'huai', difficulty: 2 },
{ pinyin: 'huan', difficulty: 2 },
{ pinyin: 'huang', difficulty: 2 },
{ pinyin: 'hui', difficulty: 2 },
{ pinyin: 'hun', difficulty: 2 },
{ pinyin: 'huo', difficulty: 2 },

// j / q / x (alveolo-palatal)
{ pinyin: 'ji', difficulty: 3 },
{ pinyin: 'jia', difficulty: 3 },
{ pinyin: 'jian', difficulty: 4 },
{ pinyin: 'jiang', difficulty: 4 },
{ pinyin: 'jiao', difficulty: 4 },
{ pinyin: 'jie', difficulty: 3 },
{ pinyin: 'jin', difficulty: 4 },
{ pinyin: 'jing', difficulty: 4 },
{ pinyin: 'jiong', difficulty: 4 },
{ pinyin: 'jiu', difficulty: 3 },
{ pinyin: 'ju', difficulty: 5 },
{ pinyin: 'juan', difficulty: 5 },
{ pinyin: 'jue', difficulty: 5 },
{ pinyin: 'jun', difficulty: 5 },

{ pinyin: 'qi', difficulty: 3 },
{ pinyin: 'qia', difficulty: 3 },
{ pinyin: 'qian', difficulty: 4 },
{ pinyin: 'qiang', difficulty: 4 },
{ pinyin: 'qiao', difficulty: 4 },
{ pinyin: 'qie', difficulty: 3 },
{ pinyin: 'qin', difficulty: 4 },
{ pinyin: 'qing', difficulty: 4 },
{ pinyin: 'qiong', difficulty: 4 },
{ pinyin: 'qiu', difficulty: 3 },
{ pinyin: 'qu', difficulty: 5 },
{ pinyin: 'quan', difficulty: 5 },
{ pinyin: 'que', difficulty: 5 },
{ pinyin: 'qun', difficulty: 5 },

{ pinyin: 'xi', difficulty: 3 },
{ pinyin: 'xia', difficulty: 3 },
{ pinyin: 'xian', difficulty: 4 },
{ pinyin: 'xiang', difficulty: 4 },
{ pinyin: 'xiao', difficulty: 4 },
{ pinyin: 'xie', difficulty: 3 },
{ pinyin: 'xin', difficulty: 4 },
{ pinyin: 'xing', difficulty: 4 },
{ pinyin: 'xiong', difficulty: 4 },
{ pinyin: 'xiu', difficulty: 3 },
{ pinyin: 'xu', difficulty: 5 },
{ pinyin: 'xuan', difficulty: 5 },
{ pinyin: 'xue', difficulty: 5 },
{ pinyin: 'xun', difficulty: 5 },

// zh / ch / sh / r (retroflex)
{ pinyin: 'zha', difficulty: 4 },
{ pinyin: 'zhai', difficulty: 4 },
{ pinyin: 'zhan', difficulty: 4 },
{ pinyin: 'zhang', difficulty: 4 },
{ pinyin: 'zhao', difficulty: 4 },
{ pinyin: 'zhe', difficulty: 4 },
{ pinyin: 'zhen', difficulty: 4 },
{ pinyin: 'zheng', difficulty: 4 },
{ pinyin: 'zhi', difficulty: 5 },
{ pinyin: 'zhong', difficulty: 4 },
{ pinyin: 'zhou', difficulty: 4 },
{ pinyin: 'zhu', difficulty: 4 },
{ pinyin: 'zhua', difficulty: 4 },
{ pinyin: 'zhuai', difficulty: 4 },
{ pinyin: 'zhuan', difficulty: 4 },
{ pinyin: 'zhuang', difficulty: 4 },
{ pinyin: 'zhui', difficulty: 4 },
{ pinyin: 'zhun', difficulty: 4 },
{ pinyin: 'zhuo', difficulty: 4 },

{ pinyin: 'cha', difficulty: 4 },
{ pinyin: 'chai', difficulty: 4 },
{ pinyin: 'chan', difficulty: 4 },
{ pinyin: 'chang', difficulty: 4 },
{ pinyin: 'chao', difficulty: 4 },
{ pinyin: 'che', difficulty: 4 },
{ pinyin: 'chen', difficulty: 4 },
{ pinyin: 'cheng', difficulty: 4 },
{ pinyin: 'chi', difficulty: 5 },
{ pinyin: 'chong', difficulty: 4 },
{ pinyin: 'chou', difficulty: 4 },
{ pinyin: 'chu', difficulty: 4 },
{ pinyin: 'chua', difficulty: 4 },
{ pinyin: 'chuai', difficulty: 4 },
{ pinyin: 'chuan', difficulty: 4 },
{ pinyin: 'chuang', difficulty: 4 },
{ pinyin: 'chui', difficulty: 4 },
{ pinyin: 'chun', difficulty: 4 },
{ pinyin: 'chuo', difficulty: 4 },

{ pinyin: 'sha', difficulty: 4 },
{ pinyin: 'shai', difficulty: 4 },
{ pinyin: 'shan', difficulty: 4 },
{ pinyin: 'shang', difficulty: 4 },
{ pinyin: 'shao', difficulty: 4 },
{ pinyin: 'she', difficulty: 4 },
{ pinyin: 'shen', difficulty: 4 },
{ pinyin: 'sheng', difficulty: 4 },
{ pinyin: 'shi', difficulty: 5 },
{ pinyin: 'shou', difficulty: 4 },
{ pinyin: 'shu', difficulty: 4 },
{ pinyin: 'shua', difficulty: 4 },
{ pinyin: 'shuai', difficulty: 4 },
{ pinyin: 'shuan', difficulty: 4 },
{ pinyin: 'shuang', difficulty: 4 },
{ pinyin: 'shui', difficulty: 4 },
{ pinyin: 'shun', difficulty: 4 },
{ pinyin: 'shuo', difficulty: 4 },

{ pinyin: 'ri', difficulty: 5 },

// z / c / s (apical vowel)
{ pinyin: 'za', difficulty: 3 },
{ pinyin: 'zai', difficulty: 3 },
{ pinyin: 'zan', difficulty: 3 },
{ pinyin: 'zang', difficulty: 3 },
{ pinyin: 'zao', difficulty: 3 },
{ pinyin: 'ze', difficulty: 3 },
{ pinyin: 'zei', difficulty: 3 },
{ pinyin: 'zen', difficulty: 3 },
{ pinyin: 'zeng', difficulty: 3 },
{ pinyin: 'zi', difficulty: 5 },
{ pinyin: 'zong', difficulty: 3 },
{ pinyin: 'zou', difficulty: 3 },
{ pinyin: 'zu', difficulty: 3 },
{ pinyin: 'zuan', difficulty: 3 },
{ pinyin: 'zui', difficulty: 3 },
{ pinyin: 'zun', difficulty: 3 },
{ pinyin: 'zuo', difficulty: 3 },

{ pinyin: 'ca', difficulty: 3 },
{ pinyin: 'cai', difficulty: 3 },
{ pinyin: 'can', difficulty: 3 },
{ pinyin: 'cang', difficulty: 3 },
{ pinyin: 'cao', difficulty: 3 },
{ pinyin: 'ce', difficulty: 3 },
{ pinyin: 'cen', difficulty: 3 },
{ pinyin: 'ceng', difficulty: 3 },
{ pinyin: 'ci', difficulty: 5 },
{ pinyin: 'cong', difficulty: 3 },
{ pinyin: 'cou', difficulty: 3 },
{ pinyin: 'cu', difficulty: 3 },
{ pinyin: 'cuan', difficulty: 3 },
{ pinyin: 'cui', difficulty: 3 },
{ pinyin: 'cun', difficulty: 3 },
{ pinyin: 'cuo', difficulty: 3 },

{ pinyin: 'sa', difficulty: 3 },
{ pinyin: 'sai', difficulty: 3 },
{ pinyin: 'san', difficulty: 3 },
{ pinyin: 'sang', difficulty: 3 },
{ pinyin: 'sao', difficulty: 3 },
{ pinyin: 'se', difficulty: 3 },
{ pinyin: 'sen', difficulty: 3 },
{ pinyin: 'seng', difficulty: 3 },
{ pinyin: 'si', difficulty: 5 },
{ pinyin: 'song', difficulty: 3 },
{ pinyin: 'sou', difficulty: 3 },
{ pinyin: 'su', difficulty: 3 },
{ pinyin: 'suan', difficulty: 3 },
{ pinyin: 'sui', difficulty: 3 },
{ pinyin: 'sun', difficulty: 3 },
{ pinyin: 'suo', difficulty: 3 },
];

/**
 * Get syllables filtered by difficulty range
 */
export function getSyllablesByDifficulty(minDiff: number, maxDiff: number): Syllable[] {
  return SYLLABLE_INVENTORY.filter(s => s.difficulty >= minDiff && s.difficulty <= maxDiff);
}

/**
 * Get syllables excluding a specific set
 */
export function filterExcludedSyllables(syllables: Syllable[], excluded: Set<string>): Syllable[] {
  return syllables.filter(s => !excluded.has(s.pinyin));
}
